version: '3'
services:
  node-app:
    container_name: express-container
    build: .
    volumes: 
      - ./src:/app/src:ro
    ports:
      - "4000:4000"
    environment:
      - Port=4000
      - Node_env="production"
    env_file:
      - ./.env 